In [1]:
import numpy as np
import pandas as pd


In [2]:
url = 'https://bit.ly/HDSC-StageOneDataset'
df = pd.read_csv(url)
print(df.head())

                record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
4             chickasaw                 gas       mcf          40533.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0               16.590                      18.59   
1               16.592                      18.58   
2               24.130             

In [3]:
print(df.columns.values)
print('no of null values = ', df.isnull().values.sum())

['record_id' 'utility_id_ferc1' 'report_year' 'plant_name_ferc1'
 'fuel_type_code_pudl' 'fuel_unit' 'fuel_qty_burned' 'fuel_mmbtu_per_unit'
 'fuel_cost_per_unit_burned' 'fuel_cost_per_unit_delivered'
 'fuel_cost_per_mmbtu']
no of null values =  180


In [4]:
print(df.isnull().sum())

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64


In [5]:
print(df.isnull().sum())

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64


In [6]:
b = df['fuel_mmbtu_per_unit'].describe().transpose()
print(b)

count    29523.000000
mean         8.492111
std         10.600220
min          0.000001
25%          1.024000
50%          5.762694
75%         17.006000
max        341.260000
Name: fuel_mmbtu_per_unit, dtype: float64


In [7]:
from scipy.stats import kurtosis, skew
c = df['fuel_qty_burned']
print('skew = {:.2f} and kurtosis = {:.2f}'.format(skew(c), kurtosis(c)))

skew = 15.85 and kurtosis = 651.26


In [8]:
print(df.isnull().sum())
print(df['fuel_unit'].dtypes)

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64
object


In [12]:
print('total no of rows: ', len(df))
per = 100.0 * 150 / len(df)
print('percentage = {:.3f} '.format(per))

total no of rows:  29523
percentage = 0.508 


In [14]:
d = df['fuel_cost_per_unit_burned']
e = df['utility_id_ferc1']
print(e.corr(d))

-0.037862707599972574


In [15]:
f = df['report_year']
print(f.corr(d))

0.013599134438134155


In [16]:
g = df['fuel_qty_burned']
print(g.corr(d))

-0.018535416794825232


In [17]:
h = df['fuel_mmbtu_per_unit']
print(h.corr(d))

-0.010033808428853078


In [18]:
i = df['fuel_cost_per_unit_delivered']
print(i.corr(d))

0.011007403299165122


In [19]:
j = df['fuel_cost_per_mmbtu']
print(j.corr(d))

-0.0004372104439703997


In [20]:
A = [1,2,3,4,5,6]
B = [13, 21, 34]
A.extend(B)
print(A)

[1, 2, 3, 4, 5, 6, 13, 21, 34]


In [21]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
a = df.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].mean()
print(a)

fuel_type_code_pudl
coal         67.421830
gas          13.659397
nuclear    4955.157002
oil         168.877086
other        18.253856
waste        19.518122
Name: fuel_cost_per_unit_burned, dtype: float64


In [24]:
b = df.groupby('report_year')['fuel_cost_per_unit_delivered'].mean()
print(b)

report_year
1994       63.636060
1995       32.735269
1996     9196.705948
1997    11140.197239
1998      287.154420
1999       25.551627
2000      985.362877
2001       60.050396
2002       47.594361
2003       55.663493
2004      139.524275
2005       41.438184
2006       38.657484
2007       43.325023
2008       58.588197
2009      652.694163
2010       91.862105
2011       59.774667
2012       60.994502
2013      172.307591
2014      192.737183
2015      326.535511
2016      103.901761
2017       46.196861
2018      499.269966
Name: fuel_cost_per_unit_delivered, dtype: float64
